services:
  php8.3-fpm:
    image: php:8.3-fpm
    container_name: php8.3-fpm
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    environment:
      PHP_MEMORY_LIMIT: 512M
